### ISSUE TITLE
Calling chart.draw(newData) does not update tree.

### ISSUE THREAD

**Issue by basgren** [bansaghi/d3.chart.layout.hierarchy#3]
Hi @bansaghi !
It seems that when I create a tree chart, it's rendered fine, but then when I get new tree data and pass them to chart.draw() function, nothing is updated. I found that the reason is in `cluster-tree.cartesian.js` file in `transform` method. Here's what stops tree from updating:

```js
if( ! chart.root ) {
  chart.root    = root;
  chart.root.x0 = chart._height / 2;
  chart.root.y0 = 0;

  nodes = chart.d3.layout
    .size([chart._height, chart._width])
    .nodes(chart.root); // workaround for getting correct chart.root to transform method in hierarchy.js

  chart.trigger("collapse:init");
}
```
When I remove `if`, updating works fine.
Could you please explain if this condition is needed? And what's the problem with transform method in hierarchy.js?

Thank you!

**Comment by bansaghi** [comment]
Hi @basgren !

Спасибо за reporting bugs :)

1. Some kind of condition is needed for differentiating between the first draw and all the other redraws. If you remove the condition then the collapse feature will go wrong.
My mistake was using an inappropriate condition, so it has changed to another. Although checking `chart.root._id` is hackish for me. I am going to think about a more elegant way.

2. Yes, there is no need to extend the `transform` method in `hierarchy.js`.

If you would be so kind to check the fix on your files too. (I am discovering the branches and workflows of GitHub projects right now, so sorry if I ruined something.)

**Comment by basgren** [comment]
Wow! Do you speak russian?))) I was surprised :)

Thank you for the clarification and fast response! Currently I'm figuring out how all this d3.chart and tree works, so any information is much appreciated. I hope I'll be able to look at your changes this weekend, but in nay case I will keep you informed.

Thanks again for your help!
